spring.application.name=biblioteca
spring.profiles.default=none

spring.datasource.url=${DB_DEV_URL}
spring.datasource.username=${DB_DEV_USERNAME}
spring.datasource.password=${DB_DEV_PASSWORD}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
